### PR TITLE
Add setuid, setgid and sticky permission bits

### PR DESCRIPTION
**Pull request by cschierig**
This pr adds support for setting and displaying the `setuid`, `setgid` and `sticky` permission bits. Display functionality has already been implemented, but I'm not done yet, so please tell me if you don't want this functionality in the crate so that I don't waste my time.

To-do:
- [x] Extra Permissions
- [x] Display
- [x] Integrate extra permissions into mode and with functions
- [ ] ~*create an example?*~
- [x] Check non unix compatibility

### CODE REVIEW

**Comment by Canop** [comment]
No opinion yet on the implementation but I'm OK with the functionality.

Don't forget documentation and unit tests for a beautiful PR.

**Comment by Canop** [comment]
I'm not sure everybody always wants to display the extra bits.

Even if they're present in the Display impl, we should keep a way display with only 'x'/'-'. Maybe with a function `without_any_extra` (removing the extra bits, which could be called before `to_string()`) and the appropriate documentation ?

I'm a little annoyed by the fact it might be considered as a regression by people checking whether a char is a 'x' or not. This might probably be covered by incrementing the major version and improving the documentation, maybe.

**Comment by cschierig** [comment]
As I've added a Class for the extra bits, I could also implement more generic `with_class` and `without_class` functions that modify all bits for a specific class. This would also be useful for setting e.g. rwx for the owner with one function. I'm not sure about the name though.
I don't know how to do that, but I could also try to make this a feature, then it would have to be enabled manually and it wouldn't break anything existing.

Other than that, I've found a problem with the documentation, but I think I'll create another pr for that to keep things clean:
```rust
/// return a new mode, with the permission removed for the class
/// (does nothing if the permission is already given to that class)
#[inline(always)]
pub const fn without_class_perm(self, class: Class, perm: Permission) -> Self {
```
I think the second line should say "(does nothing if the permission is not given to that class)".

**Comment by Canop** [comment]
I'd rather not define cargo features just for that: they're painful to use when there are too many of them. It should be OK with good documentation, major increment, and a function to make it easy to keep the old behaviour.

**Comment by cschierig** [comment]
Ok, great! Should I go with the `without_any_extra` approach or the one I proposed?

**Comment by Canop** [comment]
I personally prefer  `without_any_extra`, which should keep the whole simpler and easier to grasp for newcomers.
But I suggest we wait for a few hours before deciding, just in case some of the devs I pinged give more insights or opinions.

**Comment by Canop** [comment]
OK. I'm for going this road. Do you want to add a commit or two or do I take it from there to add the missing method, docs, etc. ?

**Comment by cschierig** [comment]
I've already finished most of it yesterday, just need to add a bit more documentation and push.

**Comment by cschierig** [comment]
That's it from my side. You can take it from here

**Comment by Canop** [comment]
It seems OK. I'll soon release a 2.0

**Comment by Canop** [comment]
@CozyPenguin your addition is available in umask 2.0.0
There's now a CHANGELOG to point to what could be seen as a regression

**Pull request merged**
