### PR TITLE
Implement Mode::parse

### PR DESCRIPTION
**Pull request by flxo**
Parse a mode from a AsRef<str>.

### CODE REVIEW

**Comment by Canop** [comment]
This looks good.

(beware GitHub rendering of what looks like HTML)

**Comment by Canop** [comment]
I merged and added a FromStr impl. It it looks OK to you, I'll release 2.1

**Comment by flxo** [comment]
Perfect. Thanks for your fast response. LGTM!

**Comment by Canop** [comment]
version 2.1.0 released to crates.io

**Pull request merged**
